server:
  port: 3000
  servlet:
    context-path: /
security:
  oauth2:
    client:
      clientId: omicuser
      clientSecret: mysecretpassword
      accessTokenUri: https://nomis-oauth2-server.herokuapp.com/auth/oauth/token
      userAuthorizationUri: https://nomis-oauth2-server.herokuapp.com/auth/oauth/authorize
    resource:
        userInfoUri: https://nomis-oauth2-server.herokuapp.com/auth/api/user/me
spring:
  thymeleaf:
    cache: false

  application:
     name: Sample SSO Client

logging:
  level:
    org.springframework: DEBUG