server:
  port: 8081
  servlet:
    context-path: /
security:
  oauth2:
    client:
      clientId: elite2apiclient
      clientSecret: clientsecret
      accessTokenUri: http://localhost:9090/auth/oauth/token
      userAuthorizationUri: http://localhost:9090/auth/oauth/authorize
    resource:
        userInfoUri: http://localhost:9090/auth/api/user/me
spring:
  thymeleaf:
    cache: false

  application:
     name: Sample SSO Client

logging:
  level:
    org.springframework: DEBUG